### ISSUE TITLE
gray color for full stations is not ok

### ISSUE THREAD

**Issue by josmardias** [josmardias/bike-vitoria#9]
A simple user test with @rafaelprado showed that gray color for "full stations" is not working.
It seems that the station is offline or something like it.

We could change it for yellow
![screenshot from 2016-07-11 09-50-39](https://cloud.githubusercontent.com/assets/413430/16731144/f26a82ea-474c-11e6-8d03-65f46518424b.png)

or magenta (there is no orange available)
![screenshot from 2016-07-11 09-49-38](https://cloud.githubusercontent.com/assets/413430/16731104/cf6c796a-474c-11e6-885f-037ec20e1453.png)

Or maybe create a another column with symbols?

@vitormil what you think?

**Comment by vitormil** [comment]
great!
